//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectiveDAL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectiveDAL.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be a tutor, he doesn&apos;t have appropriate role.
        /// </summary>
        internal static string CannotBeTutor {
            get {
                return ResourceManager.GetString("CannotBeTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course already in subject.
        /// </summary>
        internal static string CourseAlreadyInSubject {
            get {
                return ResourceManager.GetString("CourseAlreadyInSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course ID not found.
        /// </summary>
        internal static string CourseIdNotFound {
            get {
                return ResourceManager.GetString("CourseIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course {0} does not exist.
        /// </summary>
        internal static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course is not in subject.
        /// </summary>
        internal static string CourseNotInSubject {
            get {
                return ResourceManager.GetString("CourseNotInSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {0} is already taken for another subject.
        /// </summary>
        internal static string DuplicateSubjectName {
            get {
                return ResourceManager.GetString("DuplicateSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {0} should contain only letters.
        /// </summary>
        internal static string NameShouldContainOnlyLetters {
            get {
                return ResourceManager.GetString("NameShouldContainOnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} too long.
        /// </summary>
        internal static string PropertyIsTooLong {
            get {
                return ResourceManager.GetString("PropertyIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property too short.
        /// </summary>
        internal static string PropertyTooShort {
            get {
                return ResourceManager.GetString("PropertyTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} does not exist.
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date {0} is later than end date {1}.
        /// </summary>
        internal static string StartDateIsLaterThanEndDate {
            get {
                return ResourceManager.GetString("StartDateIsLaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement interface {0}.
        /// </summary>
        internal static string StoreDoesNotImplementInterface {
            get {
                return ResourceManager.GetString("StoreDoesNotImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement ICourseSubjectStore.
        /// </summary>
        internal static string StoreNotICourseSubjectStore {
            get {
                return ResourceManager.GetString("StoreNotICourseSubjectStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IElectiveUserCourseStore.
        /// </summary>
        internal static string StoreNotIElectiveUserCourseStore {
            get {
                return ResourceManager.GetString("StoreNotIElectiveUserCourseStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableCourseStore.
        /// </summary>
        internal static string StoreNotIQueryableCourseStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableCourseStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableSubjectStore.
        /// </summary>
        internal static string StoreNotIQueryableSubjectStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableSubjectStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserCourseStore.
        /// </summary>
        internal static string StoreNotIUserCourseStore {
            get {
                return ResourceManager.GetString("StoreNotIUserCourseStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name not found.
        /// </summary>
        internal static string SubjectNameNotFound {
            get {
                return ResourceManager.GetString("SubjectNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject {0} does not exist..
        /// </summary>
        internal static string SubjectNotFound {
            get {
                return ResourceManager.GetString("SubjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already banned.
        /// </summary>
        internal static string UserAlreadyBanned {
            get {
                return ResourceManager.GetString("UserAlreadyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already in course.
        /// </summary>
        internal static string UserAlreadyInCourse {
            get {
                return ResourceManager.GetString("UserAlreadyInCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already unbanned.
        /// </summary>
        internal static string UserAlreadyUnbanned {
            get {
                return ResourceManager.GetString("UserAlreadyUnbanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId not found.
        /// </summary>
        internal static string UserIdNotFound {
            get {
                return ResourceManager.GetString("UserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not a tutor.
        /// </summary>
        internal static string UserIsNotATutor {
            get {
                return ResourceManager.GetString("UserIsNotATutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in course.
        /// </summary>
        internal static string UserNotInCourse {
            get {
                return ResourceManager.GetString("UserNotInCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty.
        /// </summary>
        internal static string ValueCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrEmpty", resourceCulture);
            }
        }
    }
}
